import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { generateMetadata as genMeta } from '@/lib/seo'
import { getBreadcrumbSchema } from '@/lib/schema'
import type { Locale, SectorItem } from '@/types'

import SiteLayout from '@/components/layout/SiteLayout'
import SchemaOrg from '@/components/shared/SchemaOrg'
import CTASection from '@/components/shared/CTASection'
import SectorsIndex from '@/components/sections/sectors/SectorsIndex'

import esMessages from '@/messages/es.json'
import enMessages from '@/messages/en.json'

type Messages = typeof esMessages
function getMsg(locale: string): Messages {
  return locale === 'en' ? (enMessages as unknown as Messages) : esMessages
}

type Props = { params: Promise<{ locale: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params
  const m    = getMsg(locale)
  const sc   = m.sectors
  const isEs = locale === 'es'
  return genMeta({
    title:       sc.hero.label,
    description: sc.hero.subheadline,
    canonical:   isEs ? `/es/sectores/` : `/en/sectors/`,
    alternates:  { es: '/es/sectores/', en: '/en/sectors/' },
  }, locale as Locale)
}

export default async function SectoresPage({ params }: Props) {
  const { locale } = await params
  if (!routing.locales.includes(locale as Locale)) notFound()

  const m    = getMsg(locale)
  const sc   = m.sectors
  const isEs = locale === 'es'
  const basePath    = isEs ? `/${locale}/sectores` : `/${locale}/sectors`
  const contactHref = isEs ? `/${locale}/contacto` : `/${locale}/contact`

  const sectors = sc.items as unknown as SectorItem[]

  const breadcrumb = getBreadcrumbSchema([
    { name: m.common.breadcrumb.home, url: `/${locale}/` },
    { name: sc.hero.label,            url: basePath },
  ])

  return (
    <>
      <SchemaOrg schema={breadcrumb} />
      <SiteLayout>
        <SectorsIndex
          sectors={sectors}
          basePath={basePath}
          label={sc.hero.label}
          headline={sc.hero.headline}
          subheadline={sc.hero.subheadline}
          ctaLabel={isEs ? 'Ver sector' : 'View sector'}
        />
        <CTASection
          headline={isEs
            ? 'Tu proyecto tiene un sector. Nosotros tenemos la experiencia.'
            : 'Your project has a sector. We have the expertise.'}
          primaryLabel={isEs ? 'Solicitar Diagnóstico' : 'Request Assessment'}
          primaryHref={contactHref}
          variant="light"
        />
      </SiteLayout>
    </>
  )
}

export function generateStaticParams() {
  // /sectores/ serves the ES locale only.
  // EN sectors page is generated by sectors/page.tsx
  return [{ locale: 'es' }]
}
