import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { generateMetadata as genMeta } from '@/lib/seo'
import { getBreadcrumbSchema } from '@/lib/schema'
import type { Locale, SectorItem, ServiceItem } from '@/types'

import SiteLayout from '@/components/layout/SiteLayout'
import SchemaOrg from '@/components/shared/SchemaOrg'
import CTASection from '@/components/shared/CTASection'
import PageHero from '@/components/shared/PageHero'
import SectorDetail from '@/components/sections/sectors/SectorDetail'

import esMessages from '@/messages/es.json'
import enMessages from '@/messages/en.json'

type Messages = typeof esMessages
function getMsg(locale: string): Messages {
  return locale === 'en' ? (enMessages as unknown as Messages) : esMessages
}

// ES slugs for this route — EN sectors use different slugs under /sectors/
const ES_SLUGS = ['industrial', 'data-centers', 'hospitales', 'comercial', 'infraestructura']

// All service slugs → index (ES + EN, updated for 7-item array)
const SVC_IDX: Record<string, number> = {
  'integracion-bim': 0,   'bim-integration': 0,
  'coordinacion-bim': 1,  'bim-coordination': 1,
  'sistemas-especiales': 2, 'special-systems': 2,
  'sistemas-electricos': 3, 'electrical-systems': 3,
  'gestion-informacion': 4, 'information-management': 4,
  'bim-4d': 5,
  'bim-5d': 6,
}

type Props = { params: Promise<{ locale: string; slug: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale, slug } = await params
  const m    = getMsg(locale)
  const index = ES_SLUGS.indexOf(slug)
  if (index === -1) return {}
  const sector = (m.sectors.items as unknown as SectorItem[])[index]
  const isEs   = locale === 'es'
  return genMeta({
    title:      sector.title,
    description: sector.tagline,
    canonical:  isEs ? `/es/sectores/${slug}/` : `/en/sectors/${slug}/`,
    alternates: { es: `/es/sectores/${slug}/`, en: `/en/sectors/${slug}/` },
  }, locale as Locale)
}

export default async function SectorDetailPage({ params }: Props) {
  const { locale, slug } = await params
  if (!routing.locales.includes(locale as Locale)) notFound()

  const m     = getMsg(locale)
  const index = ES_SLUGS.indexOf(slug)
  if (index === -1) notFound()

  const isEs            = locale === 'es'
  const basePath        = isEs ? `/${locale}/sectores` : `/${locale}/sectors`
  const servicesBasePath = isEs ? `/${locale}/servicios` : `/${locale}/services`
  const contactHref     = isEs ? `/${locale}/contacto`  : `/${locale}/contact`

  const sectors  = m.sectors.items  as unknown as SectorItem[]
  const services = m.services.items as unknown as ServiceItem[]
  const sector   = sectors[index]

  const relatedServices = (sector.services as unknown as string[])
    .map((sSlug) => { const i = SVC_IDX[sSlug]; return i !== undefined ? services[i] : null })
    .filter(Boolean) as ServiceItem[]

  const breadcrumb = getBreadcrumbSchema([
    { name: m.common.breadcrumb.home,  url: `/${locale}/` },
    { name: m.sectors.hero.label,      url: basePath },
    { name: sector.title,              url: `${basePath}/${slug}` },
  ])

  return (
    <>
      <SchemaOrg schema={breadcrumb} />
      <SiteLayout>
        <PageHero
          label={m.sectors.hero.label}
          headline={sector.title}
          subheadline={sector.tagline}
          breadcrumbs={[
            { label: m.common.breadcrumb.home, href: `/${locale}/` },
            { label: m.sectors.hero.label,     href: basePath },
            { label: sector.title },
          ]}
        />
        <SectorDetail
          sector={sector}
          relatedServices={relatedServices}
          servicesBasePath={servicesBasePath}
          contactHref={contactHref}
          locale={locale}
          labels={{
            systems:  isEs ? 'Sistemas que integramos' : 'Systems we integrate',
            services: isEs ? 'Servicios aplicados'      : 'Applied services',
            cta:      isEs ? 'Diagnóstico técnico'       : 'Technical assessment',
            back:     isEs ? 'Todos los sectores'        : 'All sectors',
          }}
        />
        <CTASection
          headline={isEs ? `¿Tienes un proyecto de ${sector.title}?` : `Do you have a ${sector.title} project?`}
          body={isEs ? 'Agenda una sesión técnica y evaluamos juntos los retos de coordinación de tu proyecto.' : 'Schedule a technical session and together we evaluate your project coordination challenges.'}
          primaryLabel={isEs ? 'Agendar Sesión Técnica' : 'Schedule Technical Session'}
          primaryHref={contactHref}
          secondaryLabel={isEs ? 'Ver Todos los Sectores' : 'View All Sectors'}
          secondaryHref={basePath}
          variant="light"
        />
      </SiteLayout>
    </>
  )
}

export function generateStaticParams() {
  // /sectores/ serves the ES locale only.
  // EN sector pages are generated by sectors/[slug]/page.tsx
  return ES_SLUGS.map((slug) => ({ locale: 'es', slug }))
}
