import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { generateMetadata as genMeta, getServicesMetadata } from '@/lib/seo'
import { getServiceSchema, getBreadcrumbSchema } from '@/lib/schema'
import type { Locale, ServiceItem } from '@/types'

import SiteLayout from '@/components/layout/SiteLayout'
import SchemaOrg from '@/components/shared/SchemaOrg'
import CTASection from '@/components/shared/CTASection'
import BreadcrumbNav from '@/components/shared/BreadcrumbNav'
import ServicesHero from '@/components/sections/services/ServicesHero'
import ServicesGrid from '@/components/sections/services/ServicesGrid'

import esMessages from '@/messages/es.json'
import enMessages from '@/messages/en.json'

type Messages = typeof esMessages
function getMsg(locale: string): Messages {
  return locale === 'en' ? (enMessages as unknown as Messages) : esMessages
}

type Props = { params: Promise<{ locale: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params
  return genMeta(getServicesMetadata(locale as Locale), locale as Locale)
}

export default async function ServicesPage({ params }: Props) {
  const { locale } = await params
  if (!routing.locales.includes(locale as Locale)) notFound()

  const m    = getMsg(locale)
  const sv   = m.services
  const isEs = locale === 'es'
  const basePath    = isEs ? `/${locale}/servicios` : `/${locale}/services`
  const contactHref = isEs ? `/${locale}/contacto`  : `/${locale}/contact`

  const services = sv.items as unknown as ServiceItem[]
  const heroData = { label: sv.hero.label, headline: sv.hero.headline, subheadline: sv.hero.subheadline }

  const schemas = [
    getBreadcrumbSchema([
      { name: m.common.breadcrumb.home, url: `/${locale}/` },
      { name: heroData.label,           url: basePath },
    ]),
    ...services.map((s) => getServiceSchema(s.title, s.shortDescription, 'BIM Integration Service')),
  ]

  return (
    <>
      <SchemaOrg schema={schemas} />
      <SiteLayout>
        <ServicesHero {...heroData} />
        <div className="bg-neutral-50 border-b border-neutral-200">
          <div className="container-section py-3">
            <BreadcrumbNav items={[{ label: m.common.breadcrumb.home, href: `/${locale}/` }, { label: heroData.label }]} />
          </div>
        </div>
        <ServicesGrid services={services} basePath={basePath} allLabel={isEs ? 'Todos' : 'All'} />
        <CTASection
          headline={isEs ? '¿No estás seguro de qué servicio necesitas?' : 'Not sure which service you need?'}
          body={isEs ? 'Iniciamos con un diagnóstico técnico gratuito para identificar exactamente qué requiere tu proyecto.' : 'We start with a free technical assessment to identify exactly what your project needs.'}
          primaryLabel={isEs ? 'Solicitar Diagnóstico' : 'Request Assessment'}
          primaryHref={contactHref}
          variant="light"
        />
      </SiteLayout>
    </>
  )
}

export function generateStaticParams() {
  // /servicios/ serves the ES locale only.
  // EN services page is generated by services/page.tsx
  return [{ locale: 'es' }]
}
